name: lokr

services:
  lokr:
    image: ghcr.io/cyanistic/lokr:main
    container_name: lokr
    restart: unless-stopped
    environment:
      LOKR_HOST: ${LOKR_HOST:-lokr.cyanistic.com}
      XDG_DATA_HOME: /data
    ports:
      - "0.0.0.0:6969:6969"
    volumes:
      - ./.data:/data
    read_only: true
    tmpfs:
      - /tmp
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges:true
    healthcheck:
      test: ["CMD", "curl", "--fail", "--silent", "http://localhost:6969/api-docs/openapi.json"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
