name: model-hotel

services:
  app:
    image: ghcr.io/hugalafutro/model-hotel:latest
    container_name: model-hotel
    labels:
      app.group: model-hotel
    ports:
      - 127.0.0.1:4006:8080
    environment:
      - DATA_DIR=/data
    volumes:
      - ./.data:/data
    restart: unless-stopped
    env_file:
      ./.env
