[[stack]]
name = "pangolin"
description = "Pangolin tunneled reverse proxy"
tags = ["edge"]
deploy = true
[stack.config]
server = "production"
git_provider = "github.com"
repo = "Cyanistic/docker-configs"
branch = "main"
run_directory = "services/pangolin"
file_paths = ["docker-compose.yml"]
compose_cmd_wrapper = "secret-run -- [[COMPOSE_COMMAND]]"
compose_cmd_wrapper_include = ["up"]
