[[stack]]
name = "shitter"
description = "Shitter Nitter fork"
tags = ["app"]
deploy = true
[stack.config]
server = "production"
git_provider = "github.com"
repo = "Cyanistic/docker-configs"
branch = "main"
run_directory = "services/shitter"
file_paths = ["docker-compose.yml"]
compose_cmd_wrapper = "secret-run -- ./materialize-config.sh [[COMPOSE_COMMAND]]"
compose_cmd_wrapper_include = ["up"]
